name = "ChatThemAll"
uuid = "d20e7657-e361-40d3-9674-24e82b8f1914"
authors = ["azzaare <jf@baffier.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
